<?php

declare(strict_types=1);

use Avc\Controllers\Admin\AiLeadsController;
use Avc\Controllers\Admin\AuthController;
use Avc\Controllers\Admin\ContentEditorController;
use Avc\Controllers\Admin\ContentLibraryController;
use Avc\Controllers\Admin\ContentPipelineController;
use Avc\Controllers\Admin\DashboardController;
use Avc\Controllers\Admin\DiscountLeadsController;
use Avc\Controllers\Admin\MediaLibraryController;
use Avc\Controllers\Admin\ProductRoutingController;
use Avc\Controllers\Admin\SeoAuditController;
use Avc\Controllers\Api\AdvisorController;
use Avc\Controllers\Api\AiLeadController;
use Avc\Controllers\Api\DiscountLeadController;
use Avc\Controllers\Ops\ReadonlyController;
use Avc\Controllers\Site\ArticleCatalogController;
use Avc\Controllers\Site\AuthorityController;
use Avc\Controllers\Site\HomeController;
use Avc\Controllers\Site\ProductCatalogController;
use Avc\Controllers\Site\ReferralController;
use Avc\Controllers\Site\SeoController;

$router->get('/', [HomeController::class, 'index']);
$router->get('/en', [HomeController::class, 'index']);
$router->get('/en/', [HomeController::class, 'index']);
$router->get('/sl', [HomeController::class, 'index']);
$router->get('/sl/', [HomeController::class, 'index']);
$router->get('/forever-proizvodi', [ProductCatalogController::class, 'index']);
$router->get('/forever-proizvodi/', [ProductCatalogController::class, 'index']);
$router->get('/en/forever-products', [ProductCatalogController::class, 'index']);
$router->get('/en/forever-products/', [ProductCatalogController::class, 'index']);
$router->get('/sl/forever-izdelki', [ProductCatalogController::class, 'index']);
$router->get('/sl/forever-izdelki/', [ProductCatalogController::class, 'index']);
$router->get('/clanci', [ArticleCatalogController::class, 'index']);
$router->get('/clanci/', [ArticleCatalogController::class, 'index']);
$router->get('/en/articles', [ArticleCatalogController::class, 'index']);
$router->get('/en/articles/', [ArticleCatalogController::class, 'index']);
$router->get('/sl/clanki', [ArticleCatalogController::class, 'index']);
$router->get('/sl/clanki/', [ArticleCatalogController::class, 'index']);
$router->get('/articles', [ArticleCatalogController::class, 'redirectToHr']);
$router->get('/articles/', [ArticleCatalogController::class, 'redirectToHr']);
$router->get('/proizvodi', [ProductCatalogController::class, 'redirectToHr']);
$router->get('/proizvodi/', [ProductCatalogController::class, 'redirectToHr']);
$router->get('/shop', [ProductCatalogController::class, 'redirectToHr']);
$router->get('/shop/', [ProductCatalogController::class, 'redirectToHr']);
$router->get('/web-shop', [ProductCatalogController::class, 'redirectToHr']);
$router->get('/web-shop/', [ProductCatalogController::class, 'redirectToHr']);
$router->get('/checkout', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/checkout/', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/placanje', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/placanje/', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/my-account', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/my-account/', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/kosarica-2', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/kosarica-2/', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/kosarica-3', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/kosarica-3/', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/forever-living-webshop-3/trgovina', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/forever-living-webshop-3/trgovina/', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/en/cart', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/en/cart/', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/en/checkout', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/en/checkout/', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/en/checkout-2', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/en/checkout-2/', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/en/my-account', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/en/my-account/', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/en/shopping-cart', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/en/shopping-cart/', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/en/shop', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/en/shop/', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/sl/cart', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/sl/cart/', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/sl/checkout', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/sl/checkout/', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/sl/blagajna', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/sl/blagajna/', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/sl/my-account', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/sl/my-account/', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/sl/nakupovalni-vozicek', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/sl/nakupovalni-vozicek/', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/sl/shop', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/sl/shop/', [ProductCatalogController::class, 'redirectLegacyCommerce']);
$router->get('/o-nama', [AuthorityController::class, 'about']);
$router->get('/o-nama/', [AuthorityController::class, 'about']);
$router->get('/kako-rade-preporuke', [AuthorityController::class, 'recommendations']);
$router->get('/kako-rade-preporuke/', [AuthorityController::class, 'recommendations']);
$router->get('/urednicka-politika', [AuthorityController::class, 'editorial']);
$router->get('/urednicka-politika/', [AuthorityController::class, 'editorial']);
$router->get('/en/about', [AuthorityController::class, 'about']);
$router->get('/en/about/', [AuthorityController::class, 'about']);
$router->get('/en/how-recommendations-work', [AuthorityController::class, 'recommendations']);
$router->get('/en/how-recommendations-work/', [AuthorityController::class, 'recommendations']);
$router->get('/en/editorial-policy', [AuthorityController::class, 'editorial']);
$router->get('/en/editorial-policy/', [AuthorityController::class, 'editorial']);
$router->get('/sl/o-nas', [AuthorityController::class, 'about']);
$router->get('/sl/o-nas/', [AuthorityController::class, 'about']);
$router->get('/sl/kako-delujejo-priporocila', [AuthorityController::class, 'recommendations']);
$router->get('/sl/kako-delujejo-priporocila/', [AuthorityController::class, 'recommendations']);
$router->get('/sl/uredniska-politika', [AuthorityController::class, 'editorial']);
$router->get('/sl/uredniska-politika/', [AuthorityController::class, 'editorial']);
$router->get('/forever-living-products-hrvatska-forever-belosa-info', [AuthorityController::class, 'redirectLegacyAbout']);
$router->get('/forever-living-products-hrvatska-forever-belosa-info/', [AuthorityController::class, 'redirectLegacyAbout']);
$router->get('/magazine-home', [ArticleCatalogController::class, 'redirectToHr']);
$router->get('/magazine-home/', [ArticleCatalogController::class, 'redirectToHr']);
$router->get('/en/aloe-vera-center', [AuthorityController::class, 'redirectLegacyAbout']);
$router->get('/en/aloe-vera-center/', [AuthorityController::class, 'redirectLegacyAbout']);
$router->get('/en/aloe-vera-forever-living-products-center', [AuthorityController::class, 'redirectLegacyAbout']);
$router->get('/en/aloe-vera-forever-living-products-center/', [AuthorityController::class, 'redirectLegacyAbout']);
$router->get('/sl/center-za-aloe-vero', [AuthorityController::class, 'redirectLegacyAbout']);
$router->get('/sl/center-za-aloe-vero/', [AuthorityController::class, 'redirectLegacyAbout']);
$router->get('/sl/aloe-vera-forever-living-products-center', [AuthorityController::class, 'redirectLegacyAbout']);
$router->get('/sl/aloe-vera-forever-living-products-center/', [AuthorityController::class, 'redirectLegacyAbout']);
$router->get('/_debug/home', [HomeController::class, 'debug']);
$router->get('/robots.txt', [SeoController::class, 'robots']);
$router->get('/llms.txt', [SeoController::class, 'llms']);
$router->get('/llms-full.txt', [SeoController::class, 'llmsFull']);
$router->get('/sitemap.xml', [SeoController::class, 'sitemapIndex']);
$router->get('/sitemaps/hr.xml', [SeoController::class, 'sitemapLanguage']);
$router->get('/sitemaps/en.xml', [SeoController::class, 'sitemapLanguage']);
$router->get('/sitemaps/sl.xml', [SeoController::class, 'sitemapLanguage']);
$router->get('/ops-readonly', [ReadonlyController::class, 'index']);
$router->get('/admin/login', [AuthController::class, 'loginForm']);
$router->post('/admin/login', [AuthController::class, 'login']);
$router->get('/admin/logout', [AuthController::class, 'logout']);
$router->get('/admin', [DashboardController::class, 'index']);
$router->get('/admin/content', [ContentLibraryController::class, 'content']);
$router->get('/admin/posts', [ContentLibraryController::class, 'posts']);
$router->get('/admin/products', [ContentLibraryController::class, 'products']);
$router->get('/admin/pages', [ContentLibraryController::class, 'pages']);
$router->get('/admin/content/edit', [ContentEditorController::class, 'edit']);
$router->post('/admin/content/save', [ContentEditorController::class, 'update']);
$router->post('/admin/content/featured-image', [ContentEditorController::class, 'updateFeaturedImage']);
$router->post('/admin/content/revision/restore', [ContentEditorController::class, 'restoreRevision']);
$router->post('/admin/content/generate-structured', [ContentEditorController::class, 'generateStructured']);
$router->post('/admin/content/generate-seo-basics', [ContentEditorController::class, 'generateSeoBasics']);
$router->post('/admin/content/generate-full-draft', [ContentEditorController::class, 'generateFullDraft']);
$router->get('/admin/media', [MediaLibraryController::class, 'index']);
$router->get('/admin/content-pipeline', [ContentPipelineController::class, 'index']);
$router->post('/admin/content-pipeline/run', [ContentPipelineController::class, 'run']);
$router->get('/admin/seo-audit', [SeoAuditController::class, 'index']);
$router->post('/admin/settings/referral', [DashboardController::class, 'updateReferral']);
$router->get('/admin/ai-leads', [AiLeadsController::class, 'index']);
$router->post('/admin/ai-leads/status', [AiLeadsController::class, 'updateStatus']);
$router->get('/admin/discount-leads', [DiscountLeadsController::class, 'index']);
$router->post('/admin/discount-leads/status', [DiscountLeadsController::class, 'updateStatus']);
$router->get('/admin/product-routing', [ProductRoutingController::class, 'index']);
$router->get('/admin/product-routing/edit', [ProductRoutingController::class, 'edit']);
$router->post('/admin/product-routing/save', [ProductRoutingController::class, 'update']);
$router->post('/admin/product-routing/apply-suggestion', [ProductRoutingController::class, 'applySuggestion']);
$router->get('/go/product', [ReferralController::class, 'product']);
$router->get('/go/discount', [ReferralController::class, 'discount']);
$router->post('/api/ai-leads', [AiLeadController::class, 'store']);
$router->post('/api/discount-leads', [DiscountLeadController::class, 'store']);
$router->post('/api/advisor/conversation', [AdvisorController::class, 'conversation']);
$router->post('/api/advisor/message', [AdvisorController::class, 'message']);
$router->post('/api/advisor/lead', [AdvisorController::class, 'lead']);
$router->post('/api/advisor/feedback', [AdvisorController::class, 'feedback']);
